// Powered by OnSpace.AI
// Styles for EndLiveModal
import { StyleSheet, Dimensions } from 'react-native';
import { Colors, Spacing, Radius, FontSize } from '@/constants/theme';

const { width } = Dimensions.get('window');
export const CARD_WIDTH = Math.min(width * 0.82, 320);

export const endLiveModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: '#000000AA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    width: CARD_WIDTH,
    backgroundColor: '#18181E',
    borderRadius: 28,
    paddingTop: Spacing.xxl - 8,
    paddingBottom: Spacing.lg,
    paddingHorizontal: Spacing.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2E2E3A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.6,
    shadowRadius: 30,
    elevation: 20,
    gap: Spacing.sm - 2,
  },
  iconRing: {
    position: 'absolute',
    top: -30,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#FF3B3B22',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FF3B3B55',
  },
  iconInner: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FF3B3B18',
    alignItems: 'center',
    justifyContent: 'center',
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FF3B3B22',
    paddingHorizontal: Spacing.sm + 4,
    paddingVertical: 4,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: '#FF3B3B55',
    marginTop: Spacing.sm,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.liveRed,
  },
  livePillText: {
    fontSize: FontSize.xs,
    fontWeight: '800',
    color: Colors.liveRed,
    letterSpacing: 1.5,
  },
  heading: {
    fontSize: FontSize.xl,
    fontWeight: '800',
    color: Colors.textPrimary,
    textAlign: 'center',
    marginTop: Spacing.xs,
  },
  nameHighlight: { color: Colors.primary },
  subText: {
    fontSize: FontSize.md,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginTop: 2,
  },
  endHighlight: { color: Colors.textPrimary, fontWeight: '700' },
  caption: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
    textAlign: 'center',
    marginTop: 2,
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: '#2C2C35',
    marginVertical: Spacing.sm,
  },
  btnRow: { flexDirection: 'row', gap: Spacing.sm, width: '100%' },
  keepBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.primaryDim,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.sm + 4,
    borderWidth: 1.5,
    borderColor: Colors.primary + '55',
  },
  keepBtnText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.primary,
  },
  endBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.liveRed,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.sm + 4,
    shadowColor: Colors.liveRed,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  endBtnText: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: '#fff',
  },
});
